#static site served via Nginx
FROM nginx:alpine

# Copy HTML, CSS, and JS files
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
